Typing of attributes (#37)
eclipsesource/ecore-glsp pull request #66
Opened 2019-11-21 22:00 UTC by leodennis

Resolves #37

2019-11-21 22:39 UTC, tortmayr commented
FYI: The CI build is failing because of this:
ERROR: /home/travis/build/eclipsesource/ecore-glsp/client/sprotty-ecore/src/features/edit-label-autocomplete.ts:38:13 - Missing semicolon

2019-11-22 11:08 UTC, leodennis commented
@tortmayr Yeah I saw that but I don't get it, the line is `@injectable()` and I've never seen a semicolon after that. Also the lines before and after are all correct.
![error](https://user-images.githubusercontent.com/26283266/69421078-6aca9f80-0d20-11ea-9d6d-cacce7b743fa.PNG)

2019-11-22 12:43 UTC, leodennis commented
I just deleted `@injectable()` as I did not seem to need it...

2019-11-25 10:03 UTC, CamilleLetavernier requested changes
The changes mostly look good to me; there are just a couple of small things to fix. Thanks!

2019-11-25 10:03 UTC, CamilleLetavernier commented on client/sprotty-ecore/src/features/edit-label-autocomplete.ts
> +    protected initializeContents(containerElement: HTMLElement) {
This method is invoked only once, so caching the types here is a little bit risky: any change to the model (Adding/Removing EDataTypes, or renaming an existing EDataType) won't be reflected in the list of available types. This method should probably be called every time on createAutocomplete()

2019-11-25 10:03 UTC, CamilleLetavernier commented on client/sprotty-ecore/src/features/edit-label-autocomplete.ts
> +export class EditLabelUIAutocomplete extends EditLabelUI {
injectable is an annotation; so it should be `@injectable()` (And not `injectable()` like you had in your previous commit). That's probably why the compiler complained

2019-11-25 13:17 UTC, leodennis commented on client/sprotty-ecore/src/features/edit-label-autocomplete.ts
> +    protected initializeContents(containerElement: HTMLElement) {
I overwrote the onBeforeShow method and moved the code there so the types will be fetched just before the edit label will be shown. I added an enum and changed the name and the type was available!

2019-11-25 13:35 UTC, CamilleLetavernier approved these changes

2019-11-25 13:37 UTC, merged