improved styling
eclipsesource/ecore-glsp pull request #80
Opened 2019-12-03 22:15 UTC by leodennis

fixes #56 

The only issue is the change to 
client\sprotty-ecore\src\feedback.tsx
I tried fix it so that it looks good but I have no Idea how to write it better...

2019-12-04 09:25 UTC, CamilleLetavernier requested changes
It looks much better! :)

Regarding the label feedback, can you clarify what you mean? Is it an issue about the way it looks, or the way it is implemented?

If it's about the look, here are a few examples of how label selection work in Ecore Tools:

![image](https://user-images.githubusercontent.com/16717379/70129868-ce898c80-167f-11ea-9355-eae46c0fa58f.png)

![image](https://user-images.githubusercontent.com/16717379/70129931-e4974d00-167f-11ea-863b-b2a40a488039.png)

![image](https://user-images.githubusercontent.com/16717379/70129960-f1b43c00-167f-11ea-85ac-727d5b24f0eb.png)

(For the first image, the orange is the default selection color on Linux; it would be blue on Windows)

So maybe we could use a label background color instead of a rectangle overlay; but then we may have to integrate that directly in the NodeLabelView rather than using a separate feedback element (Inserting a rectangle below the existing label might be an issue)

Also, I think we should reduce the overall size of the elements (Font size and SVG size). We can always zoom out, but having a smaller default size would be best

2019-12-04 09:25 UTC, CamilleLetavernier commented on client/sprotty-ecore/css/diagram.css
> +    alignment-baseline: mi;
"mi" is not a valid value; I don't really get this change

2019-12-04 09:25 UTC, CamilleLetavernier commented on client/sprotty-ecore/src/feedback.tsx
> +          y={-element.bounds.height / 2 - vPadding + offsetY/2-1}
Magic numbers like `-1` should be avoided

2019-12-05 14:52 UTC, leodennis commented
@CamilleLetavernier thanks for the input, I fixed the issues and found a simpler version for the feedback. The styling of the selection could be changed as well if wanted but maybe in a different issue.

2019-12-18 08:20 UTC, CamilleLetavernier approved these changes
The changes look good to me. I just noticed that the label position is off on Firefox, but that was already the case before the patch:

![image](https://user-images.githubusercontent.com/16717379/71068714-93a35080-2177-11ea-9fc2-cfe20c4a3637.png)

![image](https://user-images.githubusercontent.com/16717379/71068733-9c942200-2177-11ea-86c1-85321ba4fbed.png)

2019-12-18 08:20 UTC, merged